In [33]:
import psycopg2
import pandas as pd
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine

load_dotenv()

user = os.getenv("user")
password = os.getenv("password")
port = os.getenv("port")
host = "localhost"
database= "crypto_analytics"

try:
    conexao = psycopg2.connect(
        host = host,
        database = database,
        user = user,
        password = password,
        port = port
    )
    print("Conectado com sucesso!")
except Exception as e:
    print(repr(e))

Conectado com sucesso!

In [34]:
query = "SELECT * FROM crypto_raw;"

with conexao.cursor() as cursor:
    cursor.execute(query)

    dados_raw = cursor.fetchall()

    colunas = [desc[0] for desc in cursor.description]

conexao.close()

df_raw = pd.DataFrame(dados_raw, columns=colunas)

display(df_raw)

,id,data_coleta,payload
0,2,2026-10-04 17:23:05.093532,"{'solana': {'brl': 630.26, 'eur': 107.45, 'usd..."
1,3,2026-10-04 17:24:08.552979,"{'solana': {'brl': 630.01, 'eur': 107.41, 'usd..."
2,4,2026-10-05 23:14:23.019484,"{'solana': {'brl': 601.74, 'eur': 107.35, 'usd..."
3,5,2026-10-06 00:00:19.286381,"{'solana': {'brl': 600.77, 'eur': 107.17, 'usd..."
4,6,2026-10-10 19:10:33.042844,"{'solana': {'brl': 549.75, 'eur': 98.39, 'usd'..."
5,7,2026-10-10 19:42:42.456010,"{'solana': {'brl': 550.82, 'eur': 98.59, 'usd'..."
6,8,2026-10-10 19:44:01.089508,"{'solana': {'brl': 550.68, 'eur': 98.56, 'usd'..."
7,9,2026-10-10 20:46:47.492044,"{'solana': {'brl': 549.03, 'eur': 98.27, 'usd'..."

In [35]:
registros = []

for _, linha in df_raw.iterrows():

    payload = linha["payload"]
    data_coleta = linha["data_coleta"]

    for coin, info in payload.items():
        registros.append({
            "coin": coin,
            "usd": info["usd"],
            "usd_market_cap": info["usd_market_cap"],
            "eur": info["eur"],
            "eur_market_cap": info["eur_market_cap"],
            "brl": info["brl"],
            "brl_market_cap": info["brl_market_cap"],
            "data_coleta": data_coleta
        })

df_silver = pd.DataFrame(registros)

display(df_silver)

,coin,usd,usd_market_cap,eur,eur_market_cap,brl,brl_market_cap,data_coleta
0,solana,120.960000,7.115170e+10,107.450000,6.320505e+10,630.260000,3.707288e+11,2026-10-04 17:23:05.093532
1,bitcoin,85473.000000,1.717318e+12,75927.000000,1.525518e+12,445349.000000,8.947913e+12,2026-10-04 17:23:05.093532
2,cardano,0.251861,9.444409e+09,0.223732,8.389601e+09,1.310000,4.920915e+10,2026-10-04 17:23:05.093532
3,ripples,0.001972,1.676277e+05,0.001752,1.489060e+05,0.010275,8.734071e+05,2026-10-04 17:23:05.093532
4,ethereum,2702.340000,3.299414e+11,2400.530000,2.930916e+11,14080.270000,1.719127e+12,2026-10-04 17:23:05.093532
5,binancecoin,790.010000,1.051859e+11,701.770000,9.343812e+10,4116.250000,5.480607e+11,2026-10-04 17:23:05.093532
6,solana,120.910000,7.113206e+10,107.410000,6.318760e+10,630.010000,3.706265e+11,2026-10-04 17:24:08.552979
7,bitcoin,85468.000000,1.717360e+12,75922.000000,1.525555e+12,445321.000000,8.948130e+12,2026-10-04 17:24:08.552979
8,cardano,0.251603,9.444898e+09,0.223503,8.390035e+09,1.310000,4.921170e+10,2026-10-04 17:24:08.552979
9,ripples,0.001972,1.676277e+05,0.001752,1.489060e+05,0.010275,8.734071e+05,2026-10-04 17:24:08.552979
10,ethereum,2702.060000,3.299209e+11,2400.280000,2.930734e+11,14078.810000,1.719020e+12,2026-10-04 17:24:08.552979
11,binancecoin,790.060000,1.051867e+11,701.820000,9.343885e+10,4116.530000,5.480650e+11,2026-10-04 17:24:08.552979
12,solana,120.410000,7.084657e+10,107.350000,6.316064e+10,601.740000,3.540533e+11,2026-10-05 23:14:23.019484
13,bitcoin,85493.000000,1.717900e+12,76218.000000,1.531530e+12,427249.000000,8.585147e+12,2026-10-05 23:14:23.019484
14,cardano,0.268259,1.007078e+10,0.239156,8.978235e+09,1.340000,5.032840e+10,2026-10-05 23:14:23.019484
15,ripples,0.001972,1.676277e+05,0.001758,1.494422e+05,0.009855,8.377135e+05,2026-10-05 23:14:23.019484
16,ethereum,2702.950000,3.300500e+11,2409.710000,2.942439e+11,13507.880000,1.649414e+12,2026-10-05 23:14:23.019484
17,binancecoin,780.640000,1.039487e+11,695.950000,9.267162e+10,3901.200000,5.194801e+11,2026-10-05 23:14:23.019484
18,solana,120.180000,7.071391e+10,107.170000,6.305644e+10,600.770000,3.534847e+11,2026-10-06 00:00:19.286381
19,bitcoin,85501.000000,1.718058e+12,76242.000000,1.532013e+12,427403.000000,8.588226e+12,2026-10-06 00:00:19.286381
20,cardano,0.266499,1.000472e+10,0.237640,8.921330e+09,1.330000,5.001160e+10,2026-10-06 00:00:19.286381
21,ripples,0.001972,1.676277e+05,0.001759,1.494756e+05,0.009858,8.379371e+05,2026-10-06 00:00:19.286381
22,ethereum,2701.380000,3.298662e+11,2408.850000,2.941457e+11,13503.640000,1.648935e+12,2026-10-06 00:00:19.286381
23,binancecoin,781.000000,1.039968e+11,696.420000,9.273520e+10,3904.050000,5.198592e+11,2026-10-06 00:00:19.286381
24,solana,110.230000,6.491153e+10,98.390000,5.794120e+10,549.750000,3.237301e+11,2026-10-10 19:10:33.042844
25,bitcoin,82971.000000,1.667466e+12,74062.000000,1.488410e+12,413798.000000,8.316068e+12,2026-10-10 19:10:33.042844
26,cardano,0.252870,9.495066e+09,0.225716,8.475467e+09,1.260000,4.735427e+10,2026-10-10 19:10:33.042844
27,ripples,0.001972,1.676277e+05,0.001760,1.496275e+05,0.009835,8.360010e+05,2026-10-10 19:10:33.042844
28,ethereum,2507.630000,3.062603e+11,2238.360000,2.733735e+11,12506.200000,1.527397e+12,2026-10-10 19:10:33.042844
29,binancecoin,750.040000,9.988509e+10,669.500000,8.915923e+10,3740.660000,4.981519e+11,2026-10-10 19:10:33.042844
30,solana,110.450000,6.502524e+10,98.590000,5.804270e+10,550.820000,3.242971e+11,2026-10-10 19:42:42.456010
31,bitcoin,83005.000000,1.667990e+12,74092.000000,1.488878e+12,413966.000000,8.318683e+12,2026-10-10 19:42:42.456010
32,cardano,0.251520,9.443654e+09,0.224511,8.429576e+09,1.250000,4.709787e+10,2026-10-10 19:42:42.456010
33,ripples,0.001972,1.676277e+05,0.001760,1.496275e+05,0.009835,8.360010e+05,2026-10-10 19:42:42.456010
34,ethereum,2505.970000,3.060058e+11,2236.870000,2.731463e+11,12497.900000,1.526127e+12,2026-10-10 19:42:42.456010
35,binancecoin,750.620000,9.994582e+10,670.020000,8.921344e+10,3743.520000,4.984548e+11,2026-10-10 19:42:42.456010
36,solana,110.420000,6.503886e+10,98.560000,5.805486e+10,550.680000,3.243651e+11,2026-10-10 19:44:01.089508
37,bitcoin,82990.000000,1.668255e+12,74079.000000,1.489114e+12,413893.000000,8.320004e+12,2026-10-10 19:44:01.089508
38,cardano,0.251513,9.447465e+09,0.224505,8.432977e+09,1.250000,4.711687e+10,2026-10-10 19:44:01.089508
39,ripples,0.001972,1.676277e+05,0.001760,1.496275e+05,0.009835,8.360010e+05,2026-10-10 19:44:01.089508
40,ethereum,2505.860000,3.060974e+11,2236.780000,2.732281e+11,12497.360000,1.526584e+12,2026-10-10 19:44:01.089508
41,binancecoin,750.540000,9.995444e+10,669.950000,8.922114e+10,3743.150000,4.984978e+11,2026-10-10 19:44:01.089508
42,solana,110.090000,6.483001e+10,98.270000,5.786843e+10,549.030000,3.233234e+11,2026-10-10 20:46:47.492044
43,bitcoin,82941.000000,1.667062e+12,74034.000000,1.488050e+12,413645.000000,8.314056e+12,2026-10-10 20:46:47.492044
44,cardano,0.249817,9.382861e+09,0.222991,8.375311e+09,1.250000,4.679468e+10,2026-10-10 20:46:47.492044
45,ripples,0.001972,1.676277e+05,0.001760,1.496275e+05,0.009835,8.360010e+05,2026-10-10 20:46:47.492044
46,ethereum,2505.530000,3.060005e+11,2236.480000,2.731416e+11,12495.710000,1.526101e+12,2026-10-10 20:46:47.492044
47,binancecoin,750.030000,9.987712e+10,669.490000,8.915211e+10,3740.590000,4.981122e+11,2026-10-10 20:46:47.492044

In [36]:
tickers = {
    "Bitcoin":"BTC",
    "Ethereum":"ETH",
    "Solana":"SOL",
    "Ripples":"XRP",
    "Cardano":"ADA",
    "Binancecoin":"BNB"
}

df_silver["coin"] = df_silver["coin"].str.title()
df_silver["tickers"] = df_silver["coin"].map(tickers)

display(df_silver)

,coin,usd,usd_market_cap,eur,eur_market_cap,brl,brl_market_cap,data_coleta,tickers
0,Solana,120.960000,7.115170e+10,107.450000,6.320505e+10,630.260000,3.707288e+11,2026-10-04 17:23:05.093532,SOL
1,Bitcoin,85473.000000,1.717318e+12,75927.000000,1.525518e+12,445349.000000,8.947913e+12,2026-10-04 17:23:05.093532,BTC
2,Cardano,0.251861,9.444409e+09,0.223732,8.389601e+09,1.310000,4.920915e+10,2026-10-04 17:23:05.093532,ADA
3,Ripples,0.001972,1.676277e+05,0.001752,1.489060e+05,0.010275,8.734071e+05,2026-10-04 17:23:05.093532,XRP
4,Ethereum,2702.340000,3.299414e+11,2400.530000,2.930916e+11,14080.270000,1.719127e+12,2026-10-04 17:23:05.093532,ETH
5,Binancecoin,790.010000,1.051859e+11,701.770000,9.343812e+10,4116.250000,5.480607e+11,2026-10-04 17:23:05.093532,BNB
6,Solana,120.910000,7.113206e+10,107.410000,6.318760e+10,630.010000,3.706265e+11,2026-10-04 17:24:08.552979,SOL
7,Bitcoin,85468.000000,1.717360e+12,75922.000000,1.525555e+12,445321.000000,8.948130e+12,2026-10-04 17:24:08.552979,BTC
8,Cardano,0.251603,9.444898e+09,0.223503,8.390035e+09,1.310000,4.921170e+10,2026-10-04 17:24:08.552979,ADA
9,Ripples,0.001972,1.676277e+05,0.001752,1.489060e+05,0.010275,8.734071e+05,2026-10-04 17:24:08.552979,XRP
10,Ethereum,2702.060000,3.299209e+11,2400.280000,2.930734e+11,14078.810000,1.719020e+12,2026-10-04 17:24:08.552979,ETH
11,Binancecoin,790.060000,1.051867e+11,701.820000,9.343885e+10,4116.530000,5.480650e+11,2026-10-04 17:24:08.552979,BNB
12,Solana,120.410000,7.084657e+10,107.350000,6.316064e+10,601.740000,3.540533e+11,2026-10-05 23:14:23.019484,SOL
13,Bitcoin,85493.000000,1.717900e+12,76218.000000,1.531530e+12,427249.000000,8.585147e+12,2026-10-05 23:14:23.019484,BTC
14,Cardano,0.268259,1.007078e+10,0.239156,8.978235e+09,1.340000,5.032840e+10,2026-10-05 23:14:23.019484,ADA
15,Ripples,0.001972,1.676277e+05,0.001758,1.494422e+05,0.009855,8.377135e+05,2026-10-05 23:14:23.019484,XRP
16,Ethereum,2702.950000,3.300500e+11,2409.710000,2.942439e+11,13507.880000,1.649414e+12,2026-10-05 23:14:23.019484,ETH
17,Binancecoin,780.640000,1.039487e+11,695.950000,9.267162e+10,3901.200000,5.194801e+11,2026-10-05 23:14:23.019484,BNB
18,Solana,120.180000,7.071391e+10,107.170000,6.305644e+10,600.770000,3.534847e+11,2026-10-06 00:00:19.286381,SOL
19,Bitcoin,85501.000000,1.718058e+12,76242.000000,1.532013e+12,427403.000000,8.588226e+12,2026-10-06 00:00:19.286381,BTC
20,Cardano,0.266499,1.000472e+10,0.237640,8.921330e+09,1.330000,5.001160e+10,2026-10-06 00:00:19.286381,ADA
21,Ripples,0.001972,1.676277e+05,0.001759,1.494756e+05,0.009858,8.379371e+05,2026-10-06 00:00:19.286381,XRP
22,Ethereum,2701.380000,3.298662e+11,2408.850000,2.941457e+11,13503.640000,1.648935e+12,2026-10-06 00:00:19.286381,ETH
23,Binancecoin,781.000000,1.039968e+11,696.420000,9.273520e+10,3904.050000,5.198592e+11,2026-10-06 00:00:19.286381,BNB
24,Solana,110.230000,6.491153e+10,98.390000,5.794120e+10,549.750000,3.237301e+11,2026-10-10 19:10:33.042844,SOL
25,Bitcoin,82971.000000,1.667466e+12,74062.000000,1.488410e+12,413798.000000,8.316068e+12,2026-10-10 19:10:33.042844,BTC
26,Cardano,0.252870,9.495066e+09,0.225716,8.475467e+09,1.260000,4.735427e+10,2026-10-10 19:10:33.042844,ADA
27,Ripples,0.001972,1.676277e+05,0.001760,1.496275e+05,0.009835,8.360010e+05,2026-10-10 19:10:33.042844,XRP
28,Ethereum,2507.630000,3.062603e+11,2238.360000,2.733735e+11,12506.200000,1.527397e+12,2026-10-10 19:10:33.042844,ETH
29,Binancecoin,750.040000,9.988509e+10,669.500000,8.915923e+10,3740.660000,4.981519e+11,2026-10-10 19:10:33.042844,BNB
30,Solana,110.450000,6.502524e+10,98.590000,5.804270e+10,550.820000,3.242971e+11,2026-10-10 19:42:42.456010,SOL
31,Bitcoin,83005.000000,1.667990e+12,74092.000000,1.488878e+12,413966.000000,8.318683e+12,2026-10-10 19:42:42.456010,BTC
32,Cardano,0.251520,9.443654e+09,0.224511,8.429576e+09,1.250000,4.709787e+10,2026-10-10 19:42:42.456010,ADA
33,Ripples,0.001972,1.676277e+05,0.001760,1.496275e+05,0.009835,8.360010e+05,2026-10-10 19:42:42.456010,XRP
34,Ethereum,2505.970000,3.060058e+11,2236.870000,2.731463e+11,12497.900000,1.526127e+12,2026-10-10 19:42:42.456010,ETH
35,Binancecoin,750.620000,9.994582e+10,670.020000,8.921344e+10,3743.520000,4.984548e+11,2026-10-10 19:42:42.456010,BNB
36,Solana,110.420000,6.503886e+10,98.560000,5.805486e+10,550.680000,3.243651e+11,2026-10-10 19:44:01.089508,SOL
37,Bitcoin,82990.000000,1.668255e+12,74079.000000,1.489114e+12,413893.000000,8.320004e+12,2026-10-10 19:44:01.089508,BTC
38,Cardano,0.251513,9.447465e+09,0.224505,8.432977e+09,1.250000,4.711687e+10,2026-10-10 19:44:01.089508,ADA
39,Ripples,0.001972,1.676277e+05,0.001760,1.496275e+05,0.009835,8.360010e+05,2026-10-10 19:44:01.089508,XRP
40,Ethereum,2505.860000,3.060974e+11,2236.780000,2.732281e+11,12497.360000,1.526584e+12,2026-10-10 19:44:01.089508,ETH
41,Binancecoin,750.540000,9.995444e+10,669.950000,8.922114e+10,3743.150000,4.984978e+11,2026-10-10 19:44:01.089508,BNB
42,Solana,110.090000,6.483001e+10,98.270000,5.786843e+10,549.030000,3.233234e+11,2026-10-10 20:46:47.492044,SOL
43,Bitcoin,82941.000000,1.667062e+12,74034.000000,1.488050e+12,413645.000000,8.314056e+12,2026-10-10 20:46:47.492044,BTC
44,Cardano,0.249817,9.382861e+09,0.222991,8.375311e+09,1.250000,4.679468e+10,2026-10-10 20:46:47.492044,ADA
45,Ripples,0.001972,1.676277e+05,0.001760,1.496275e+05,0.009835,8.360010e+05,2026-10-10 20:46:47.492044,XRP
46,Ethereum,2505.530000,3.060005e+11,2236.480000,2.731416e+11,12495.710000,1.526101e+12,2026-10-10 20:46:47.492044,ETH
47,Binancecoin,750.030000,9.987712e+10,669.490000,8.915211e+10,3740.590000,4.981122e+11,2026-10-10 20:46:47.492044,BNB

In [38]:
conexao = psycopg2.connect(
    host= host,
    database=  database,
    user= user,
    password= password,
    port= port
)

with conexao.cursor() as cursor:

    cursor.execute("""
    INSERT INTO crypto_silver (
        id_raw,
        coin,
        ticker,
        usd,
        usd_market_cap,
        eur,
        eur_market_cap,
        brl,
        brl_market_cap,
        data_coleta)
    VALUES (
        %s,%s,%s,%s,%s,%s,%s,%s,%s
    )
    """)

    conexao.commit()

conexao.close()

SyntaxError: ERRO:  erro de sintaxe em ou próximo a "%"
LINE 14:         %s,%s,%s,%s,%s,%s,%s,%s,%s
                 ^